### ISSUE TITLE
Demo app image is not shared

### ISSUE THREAD

**Issue by psarossy** [Rookout/traefik-in-k8s-guide#1]
hi!

I was following your guide, and it seems that the image referenced is not world viewable:

us.gcr.io/rookoutdev/traefik-hello-world:latest

**Comment by MickaelAlliel** [comment]
Hi @psarossy thanks for reaching out :)
I'm assuming you're talking about step 3 of the guide - you can build the docker image yourself using the Dockerfile provided and replace the image name in the deployment.yaml of the chart in that step.

`cd step-3-install-demo-application && docker build . -t demo-app`
and replace line 16 in `traefik-in-k8s-guide/step-3-install-demo-application/hello-world-helm/templates/deployment.yaml` to `image: demo-app` or whichever container registry you will upload the image to if you are not working in a local cluster.

Hope it helps - feel free to reach out again with any issue
